services:
  postgres:
    image: postgres:16
    container_name: postgres-spotify
    environment:
      POSTGRES_USER: spotify
      POSTGRES_PASSWORD: spotify
      POSTGRES_DB: spotify_db
    ports:
      - "54322:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
